# Generated by Django 4.0.7 on 2022-10-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageDesignation', '0002_alter_designation_designationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='DesignationDesc',
            field=models.CharField(db_column='Designation_Desc', max_length=500, null=True),
        ),
    ]
