# Generated by Django 4.0.7 on 2022-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageDesignation', '0003_alter_designation_designationdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='DesignationName',
            field=models.CharField(db_column='Designation_Name', max_length=100, unique=True),
        ),
    ]
