# Generated by Django 4.0.7 on 2022-12-15 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0004_candidate_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Category',
            fields=[
                ('FeedbackCategorID', models.AutoField(db_column='Feedback_Category_ID', primary_key=True, serialize=False)),
                ('InterviewType', models.CharField(db_column='Interview_Type', max_length=40)),
                ('FeedbackCategory', models.CharField(db_column='Feedback_Category', max_length=60)),
            ],
            options={
                'db_table': 'Feedback_Category',
            },
        ),
        migrations.CreateModel(
            name='Candidate_Feedback',
            fields=[
                ('CandidateFeedbackID', models.AutoField(primary_key=True, serialize=False)),
                ('Comments', models.CharField(max_length=500, null=True)),
                ('Rating', models.IntegerField(null=True)),
                ('Candidate', models.ForeignKey(db_column='Candidate_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate')),
                ('FeedbackCategory', models.ForeignKey(db_column='Feedback_Category_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CandidateFeedback.feedback_category')),
            ],
            options={
                'db_table': 'Candidate_Feedback',
            },
        ),
    ]
