# Generated by Django 4.0.7 on 2022-12-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_category',
            name='Stage',
            field=models.CharField(db_column='Stage_Name', default='', max_length=200),
        ),
    ]
