# Generated by Django 4.0.7 on 2022-12-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFeedback', '0002_feedback_category_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_category',
            old_name='FeedbackCategorID',
            new_name='FeedbackCategoryID',
        ),
    ]
