# Generated by Django 4.0.7 on 2022-10-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.AutoField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(db_column='Customer_Name', max_length=100, null=True, unique=True)),
                ('Acronym', models.CharField(db_column='Acronym', max_length=4, null=True)),
                ('CustomerDesc', models.CharField(db_column='Customer_Description', max_length=500, null=True)),
                ('Active', models.BooleanField(db_column='Active', default=True, null=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
