# Generated by Django 4.0.7 on 2022-10-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCustomer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Acronym',
            field=models.CharField(db_column='Acronym', max_length=4, null=True, unique=True),
        ),
    ]
