# Generated by Django 4.0.7 on 2022-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCustomer', '0002_alter_customer_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Active',
            field=models.BooleanField(db_column='Active', default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerName',
            field=models.CharField(db_column='Customer_Name', default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
