# Generated by Django 4.0.8 on 2023-01-18 19:29

from django.db import migrations, models
import django.db.models.deletion
import selectedcandidate.models.Documentsupload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0012_remove_selected_candidates_ismqvariable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('Marital_status', models.CharField(blank=True, max_length=40, null=True)),
                ('Gender', models.CharField(max_length=30, null=True)),
                ('BloodGroup', models.CharField(max_length=5, null=True)),
                ('PAN', models.CharField(max_length=10, null=True)),
                ('AADHAR', models.CharField(max_length=20, null=True)),
                ('Email', models.CharField(max_length=20, null=True)),
                ('ContactNumber', models.CharField(max_length=15, null=True)),
                ('EmergencycontactName', models.CharField(max_length=40, null=True)),
                ('EmergencycontactRelation', models.CharField(max_length=20, null=True)),
                ('EmergencycontactNumber', models.CharField(max_length=20, null=True)),
                ('Passport', models.CharField(max_length=20, null=True)),
                ('PassportValidFrom', models.DateField(null=True)),
                ('PassportValidTo', models.DateField(null=True)),
                ('Address', models.CharField(max_length=500, null=True)),
                ('selectedCandidateid', models.ForeignKey(db_column='Selected_Candidate_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.selected_candidates')),
            ],
            options={
                'db_table': 'CandidatePersonalInfo',
            },
        ),
        migrations.CreateModel(
            name='CandidateInsuranceDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('Relationship', models.CharField(max_length=10, null=True)),
                ('Gender', models.CharField(max_length=5, null=True)),
                ('PercentageofInsurance', models.IntegerField(default=100, null=True)),
                ('Selected_Candidate_ID', models.ForeignKey(db_column='Selected_Candidate_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.selected_candidates')),
            ],
            options={
                'db_table': 'CandidateInsuranceDetails',
            },
        ),
        migrations.CreateModel(
            name='CandidateFamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=40, null=True)),
                ('Date_Of_Birth', models.DateField(null=True)),
                ('Relationship_with_employee', models.CharField(max_length=20, null=True)),
                ('Contact_Number', models.CharField(max_length=15, null=True)),
                ('selectedCandidateId', models.ForeignKey(db_column='selectedCandidateId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.selected_candidates')),
            ],
            options={
                'db_table': 'CandidateFamilyDetails',
            },
        ),
        migrations.CreateModel(
            name='CandidateEmployementDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PreviousCompanyName', models.CharField(default='', max_length=40)),
                ('PreviousCompanyAddress', models.CharField(default='', max_length=200, null=True)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Designationonjoining', models.CharField(max_length=20, null=True)),
                ('Designationonleaving', models.CharField(max_length=20, null=True)),
                ('selectedCandidateId', models.ForeignKey(db_column='selectedCandidateId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.selected_candidates')),
            ],
            options={
                'db_table': 'CandidateEmployementDetails',
            },
        ),
        migrations.CreateModel(
            name='CandidateEducationalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(db_column='Qualification', max_length=15)),
                ('Specialization', models.CharField(db_column='Specialization', max_length=20, null=True)),
                ('Start_Date', models.DateField(blank=True, db_column='Start_Date', null=True)),
                ('End_Date', models.DateField(blank=True, db_column='End_Date', null=True)),
                ('Institute', models.CharField(db_column='Institute', max_length=70, null=True)),
                ('Percentage', models.CharField(db_column='Percentage', max_length=5, null=True)),
                ('selectedCandidateId', models.ForeignKey(db_column='selectedCandidateId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.selected_candidates')),
            ],
            options={
                'db_table': 'CandidateEducationalDetails',
            },
        ),
        migrations.CreateModel(
            name='CandidateDocumentsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailtypeId', models.IntegerField(null=True)),
                ('detailtype', models.CharField(max_length=30)),
                ('documentpath', models.FileField(db_column='documentpath', upload_to=selectedcandidate.models.Documentsupload.CandidateDocumentsUpload.get_upload_path)),
                ('selectedCandidateId', models.ForeignKey(db_column='selectedCandidateId', on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.selected_candidates')),
            ],
            options={
                'db_table': 'CandidateDocuments',
            },
        ),
    ]
