# Generated by Django 4.0.8 on 2023-03-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedocumentsupload',
            name='verified',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
    ]
