# Generated by Django 4.0.8 on 2023-02-17 10:48

from django.db import migrations, models
import django.db.models.deletion
import selectedcandidate.models.Candidatebankdetails


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_remove_selected_candidates_candidatecategory_and_more'),
        ('selectedcandidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateBankDetails',
            fields=[
                ('Id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('BankName', models.CharField(db_column='Bank_Name', max_length=100)),
                ('AccountNumber', models.CharField(db_column='Account_Number', max_length=100)),
                ('BranchName', models.CharField(db_column='Branch_Name', max_length=100)),
                ('IFSCcode', models.CharField(db_column='IFSC_Code', max_length=100)),
                ('BankPassbook', models.FileField(db_column='Bank_Passbook', null=True, upload_to=selectedcandidate.models.Candidatebankdetails.CandidateBankDetails.get_upload_path)),
                ('selectedcandidateid', models.ForeignKey(db_column='selectedcandidateid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.selected_candidates')),
            ],
            options={
                'db_table': 'Candidate_Bank_Details',
            },
        ),
    ]
