# Generated by Django 4.0.8 on 2023-01-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatedocumentsupload',
            old_name='documentpath',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='candidatedocumentsupload',
            old_name='selectedCandidateId',
            new_name='selectedcandidate',
        ),
    ]
