# Generated by Django 4.0.8 on 2023-03-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='PhysicalHadicap',
            new_name='PhysicalHandicap',
        ),
    ]
