# Generated by Django 4.0.7 on 2023-01-31 14:54

from django.db import migrations, models
import selectedcandidate.models.Documentsupload


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0002_rename_documentpath_candidatedocumentsupload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedocumentsupload',
            name='file',
            field=models.FileField(db_column='documentpath', max_length=300, upload_to=selectedcandidate.models.Documentsupload.CandidateDocumentsUpload.get_upload_path),
        ),
        migrations.DeleteModel(
            name='CandidateInsuranceDetials',
        ),
    ]
