# Generated by Django 4.0.8 on 2023-03-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0002_rename_physicalhadicap_candidatepfdetails_physicalhandicap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepfdetails',
            name='Email',
            field=models.CharField(db_column='Email', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepfdetails',
            name='MemberNameAsPerAadhar',
            field=models.CharField(db_column='Member_Name_As_Per_Aadhar', max_length=100),
        ),
    ]
