# Generated by Django 4.0.8 on 2023-02-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0003_remove_candidateinsurancedetails_percentageofinsurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepersonalinfo',
            old_name='Passport',
            new_name='PassportNumber',
        ),
    ]
