# Generated by Django 4.0.8 on 2023-03-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0003_alter_candidatepfdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepfdetails',
            name='PhysicalHandicap',
            field=models.BooleanField(db_column='Physical_Handicap', default=False),
        ),
    ]
