# Generated by Django 4.0.8 on 2023-02-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0003_alter_candidatedocumentsupload_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedocumentsupload',
            name='verified',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
