# Generated by Django 4.0.8 on 2023-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0004_candidatedocumentsupload_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedocumentsupload',
            name='verificationcomments',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
