# Generated by Django 4.0.8 on 2023-02-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0005_alter_candidatepersonalinfo_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepfdetails',
            name='Aadhar',
            field=models.CharField(db_column='AADHAR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepfdetails',
            name='DoJ',
            field=models.CharField(db_column='Date_Of_Joining', max_length=20, null=True),
        ),
    ]
