# Generated by Django 4.0.8 on 2023-02-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0006_alter_candidatepfdetails_aadhar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='selectedCandidateid',
            new_name='selectedcandidateid',
        ),
    ]
