# Generated by Django 4.0.8 on 2023-02-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectedcandidate', '0007_rename_selectedcandidateid_candidatepfdetails_selectedcandidateid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='Aadhar',
            new_name='AADHAR',
        ),
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='BankAccNum',
            new_name='AccountNumber',
        ),
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='MobileNumber',
            new_name='ContactNumber',
        ),
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='DoB',
            new_name='DateOfBirth',
        ),
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='DoJ',
            new_name='Date_Of_Joining',
        ),
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='EmailId',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='IFSC',
            new_name='IFSCcode',
        ),
        migrations.RenameField(
            model_name='candidatepfdetails',
            old_name='MaritalStatus',
            new_name='Marital_status',
        ),
    ]
