# Generated by Django 4.0.7 on 2022-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyId', models.AutoField(db_column='Company_ID', primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(db_column='Company_Name', max_length=50, null=True)),
                ('CompanyDesc', models.CharField(db_column='Company_Desc', max_length=200, null=True)),
                ('Active', models.BooleanField(db_column='Active', default=True, null=True)),
            ],
        ),
    ]
