# Generated by Django 4.0.7 on 2022-09-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managecompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='HW_Company',
        ),
    ]
