# Generated by Django 4.0.7 on 2022-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecompany', '0003_alter_company_companyname_alter_company_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Active',
            field=models.BooleanField(db_column='Active', default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyDesc',
            field=models.CharField(db_column='Company_Desc', max_length=500, null=True),
        ),
    ]
