# Generated by Django 4.0.7 on 2022-10-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdUsers',
            fields=[
                ('Id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('UserName', models.CharField(db_column='User_Name', max_length=50)),
                ('FirstName', models.CharField(db_column='First_Name', max_length=50)),
                ('LastName', models.CharField(db_column='Last_Name', max_length=50)),
                ('Email', models.CharField(db_column='Email', max_length=100)),
                ('Active', models.BooleanField(db_column='Active', default=True)),
            ],
            options={
                'db_table': 'Ad_Users',
                'unique_together': {('UserName', 'FirstName', 'LastName', 'Email')},
            },
        ),
    ]
