# Generated by Django 4.0.7 on 2022-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageExperienceLevel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='Active',
            field=models.BooleanField(db_column='Active', default=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ExperienceLevel',
            field=models.CharField(db_column='Experience_Level', max_length=100, unique=True),
        ),
    ]
