# Generated by Django 4.0.7 on 2022-10-26 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageExperienceLevel', '0003_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='qty',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='ExperienceRange',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
