# Generated by Django 4.0.7 on 2022-10-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageExperienceLevel', '0004_remove_mymodel_qty_mymodel_experiencerange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
