# Generated by Django 4.0.7 on 2022-10-27 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageExperienceLevel', '0005_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ExperienceRange',
            field=models.IntegerField(db_column='Experience_Range', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)]),
        ),
    ]
