# Generated by Django 4.0.7 on 2022-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageExperienceLevel', '0008_remove_experience_max_experiencerange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='Max_ExperienceRange',
            field=models.IntegerField(db_column='Max_ExperienceRange', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='Min_ExperienceRange',
            field=models.IntegerField(db_column='Min_ExperienceRange', default=0),
            preserve_default=False,
        ),
    ]
