from django.db import models

class CandidateActionModel(models.Model):
    id = models.BigIntegerField(primary_key=True)
    CandidateApprovalID = models.BigIntegerField(db_column='Candidate_Approval_ID')
    RoleName = models.CharField(max_length=50, db_column='Role_Name')
    CandidateID = models.BigIntegerField(db_column='Candidate_ID')
    CandidateCode = models.CharField(max_length=100, db_column='Candidate_Code')
    CandidateFirstName = models.CharField(max_length=100, db_column='Can_First_Name')
    CandidateLastName = models.CharField(max_length=100, db_column='Can_Last_Name')
    CandidateName = models.CharField(max_length=200, db_column='Can_Name')
    ContactNo = models.CharField(max_length=10, db_column='Contact_No')
    CurrentCTC = models.IntegerField(db_column='Current_CTC')
    ExpectedCTC = models.IntegerField(db_column='Expected_CTC')
    NegotiatedCTC = models.IntegerField(db_column='Negotiated_CTC')
    Skills = models.CharField(max_length=500, db_column='Skills')
    CandidateResume = models.CharField(max_length=10000,db_column='Can_Resume')
    CurrentOrg = models.CharField(max_length=200, db_column='Current_Org')
    CurrentJobLocation = models.CharField(max_length=100, db_column='Current_Job_Loc')
    Email = models.CharField(max_length=100, db_column='Email')
    ExpectedDOJ = models.DateField(db_column='Expected_DOJ')
    CandidateReleventExp = models.CharField(max_length=50,db_column='CAN_Relevent_Exp')
    CandidateOverallExp = models.CharField(max_length=50,db_column='CAN_Overall_Exp')
    HighestQualification = models.CharField(max_length=100, db_column='High_Qualification')
    CandidateAvgApprovedCTC = models.IntegerField(db_column='Can_Avg_Approved_CTC')
    CandidateAvgBillRate = models.IntegerField(db_column='Can_Avg_Bill_Rate')
    
    # JobPostApprovalID = models.BigIntegerField(db_column='Job_Post_Approval_ID')
    JobPostID = models.BigIntegerField(db_column='Job_Post_ID')
    JobCode = models.CharField(max_length=100, db_column='Job_Code')
    UserName = models.CharField(max_length=50, db_column='User_Name')
    HiringManager = models.CharField(max_length=100, db_column='Hiring_Manager')
    ApproverName = models.CharField(max_length=50, db_column='Approver_Name')
    ApproverDisplayName = models.CharField(max_length=100, db_column='Approver_Display_Name')
    ApproverEmail = models.CharField(max_length=100, db_column='Approver_Email')    
    JobTitle =models.CharField(max_length=100, db_column='Job_Title')
    JobDesc =models.CharField(max_length=1000, db_column='Job_Desc')
    EmploymentType = models.CharField(max_length=50, db_column='Employment_Type')
    Duration = models.IntegerField(db_column='Dureation')
    NoOfPositions = models.IntegerField(db_column='No_Of_Positions')
    Qualification = models.CharField(max_length=50, db_column='Qualification')
    OnBoardingDate = models.DateField(db_column='OnBoarding_Date')
    POReference = models.CharField(max_length=50, db_column='PO_Ref')
    StageName = models.CharField(max_length=50, db_column='Stage_Name')
    StageDesc = models.CharField(max_length=100, db_column='Satge_Desc')
    IndustryName =  models.CharField(max_length=100, db_column='Industry_Name')
    CompanyName = models.CharField(max_length=50, db_column='Company_Name')
    BusinessUnitName = models.CharField(max_length=50, db_column='Business_Unit_Name')
    ServiceLineName = models.CharField(max_length=50, db_column='Service_Line_Name')
    CustomerName = models.CharField(max_length=50, db_column='Customer_Name')
    LocationName = models.CharField(max_length=50, db_column='Location_Name')
    ExperienceLevel = models.CharField(max_length=50, db_column='Experience_Level')
    AvgApprovedCTC = models.IntegerField(db_column='Avg_Approved_CTC')
    AvgBillRate = models.IntegerField(db_column='Avg_Bill_Rate')

    class Meta:   
        managed = False 
        db_table = 'view_candidateaction'