# Generated by Django 4.0.7 on 2022-10-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('BusinessUnitId', models.AutoField(db_column='Business_Unit_ID', primary_key=True, serialize=False)),
                ('CompanyId', models.IntegerField(db_column='Company_ID')),
                ('BusinessUnitName', models.CharField(db_column='Business_Unit_Name', max_length=50, unique=True)),
                ('BusinessUnitDesc', models.CharField(db_column='Business_Unit_Desc', max_length=500, null=True)),
                ('Active', models.BooleanField(db_column='Active', default=True)),
            ],
            options={
                'db_table': 'Business_Unit',
                'unique_together': {('CompanyId', 'BusinessUnitName')},
            },
        ),
    ]
