# Generated by Django 4.0.7 on 2022-10-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebusinessunit', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessunit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='CompanyId',
            field=models.IntegerField(db_column='Company_ID', unique=True),
        ),
    ]
