# Generated by Django 4.0.7 on 2022-10-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebusinessunit', '0002_alter_businessunit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='BusinessUnitName',
            field=models.CharField(db_column='Business_Unit_Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='CompanyId',
            field=models.IntegerField(db_column='Company_ID'),
        ),
        migrations.AlterUniqueTogether(
            name='businessunit',
            unique_together={('CompanyId', 'BusinessUnitName')},
        ),
    ]
