# Generated by Django 4.0.7 on 2022-12-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebusinessunit', '0003_alter_businessunit_businessunitname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='Acronym',
            field=models.CharField(db_column='Acronym', max_length=4, null=True, unique=True),
        ),
    ]
