# Generated by Django 4.0.7 on 2022-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployementType',
            fields=[
                ('EmployementTypeId', models.AutoField(db_column='EmployementTypeId', primary_key=True, serialize=False)),
                ('EmployementType', models.CharField(db_column='Employement_Type', default='', max_length=30, unique=True)),
                ('Active', models.BooleanField(db_column='Active', default=True)),
            ],
            options={
                'db_table': 'HW_Employement_Type',
            },
        ),
    ]
