# Generated by Django 4.0.7 on 2022-10-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvgCTC',
            fields=[
                ('Id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ServiceLineId', models.IntegerField(db_column='Service_Line_ID', null=True)),
                ('ExperienceLevelId', models.IntegerField(db_column='Experience_Level_ID', null=True)),
                ('AvgApprovedCTC', models.FloatField(db_column='Avg_Approved_CTC', null=True)),
                ('AvgBillRate', models.FloatField(db_column='Avg_Bill_Rate', null=True)),
            ],
            options={
                'db_table': 'AvgCTC',
            },
        ),
    ]
