# Generated by Django 4.0.7 on 2022-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageAvgCTC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgctc',
            name='AvgApprovedCTC',
            field=models.FloatField(db_column='Avg_Approved_CTC'),
        ),
        migrations.AlterField(
            model_name='avgctc',
            name='ExperienceLevelId',
            field=models.IntegerField(db_column='Experience_Level_ID'),
        ),
        migrations.AlterField(
            model_name='avgctc',
            name='ServiceLineId',
            field=models.IntegerField(db_column='Service_Line_ID'),
        ),
    ]
