# Generated by Django 4.0.7 on 2022-11-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('StageType', models.CharField(db_column='Stage_Type', max_length=50)),
                ('StageId', models.IntegerField(db_column='Stage_Id')),
                ('StageName', models.CharField(db_column='Stage_Name', max_length=50)),
                ('StageDesc', models.CharField(db_column='Satge_Desc', max_length=200)),
                ('StageRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'HW_Stage',
            },
        ),
    ]
