# Generated by Django 4.0.8 on 2023-03-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managebusinessunit', '0004_businessunit_acronym'),
        ('ManageLocation', '0004_alter_location_locationname'),
        ('ManageCustomer', '0003_alter_customer_active_alter_customer_customername'),
        ('managecompany', '0004_alter_company_active_alter_company_companydesc'),
        ('manageserviceline', '0004_alter_serviceline_unique_together_and_more'),
        ('ManageIndustry', '0002_alter_industry_active_alter_industry_industryname'),
        ('managestages', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostActionModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('JobPostApprovalID', models.BigIntegerField(db_column='Job_Post_Approval_ID')),
                ('JobPostID', models.BigIntegerField(db_column='Job_Post_ID')),
                ('JobCode', models.CharField(db_column='Job_Code', max_length=100)),
                ('UserName', models.CharField(db_column='User_Name', max_length=50)),
                ('HiringManager', models.CharField(db_column='Hiring_Manager', max_length=100)),
                ('ApproverName', models.CharField(db_column='Approver_Name', max_length=50)),
                ('ApproverDisplayName', models.CharField(db_column='Approver_Display_Name', max_length=100)),
                ('ApproverEmail', models.CharField(db_column='Approver_Email', max_length=100)),
                ('JobTitle', models.CharField(db_column='Job_Title', max_length=100)),
                ('JobDesc', models.CharField(db_column='Job_Desc', max_length=1000)),
                ('EmploymentType', models.CharField(db_column='Employment_Type', max_length=50)),
                ('Duration', models.IntegerField(db_column='Dureation')),
                ('NoOfPositions', models.IntegerField(db_column='No_Of_Positions')),
                ('Qualification', models.CharField(db_column='Qualification', max_length=50)),
                ('OnBoardingDate', models.DateField(db_column='OnBoarding_Date')),
                ('POReference', models.CharField(db_column='PO_Ref', max_length=50)),
                ('Stage', models.CharField(db_column='Stage_Name', max_length=50)),
                ('StageDesc', models.CharField(db_column='Satge_Desc', max_length=100)),
                ('industry_name', models.CharField(db_column='Industry_Name', max_length=100)),
                ('company_name', models.CharField(db_column='Company_Name', max_length=50)),
                ('businessunit_name', models.CharField(db_column='Business_Unit_Name', max_length=50)),
                ('serviceline_name', models.CharField(db_column='Service_Line_Name', max_length=50)),
                ('customer_name', models.CharField(db_column='Customer_Name', max_length=50)),
                ('Location_ID', models.IntegerField(db_column='Location_ID')),
                ('location_name', models.CharField(db_column='Location_Name', max_length=50)),
                ('AvgApprovedCTC', models.FloatField(db_column='Avg_Approved_CTC')),
                ('AvgBillRate', models.FloatField(db_column='Avg_Bill_Rate')),
                ('MaximumExperiance', models.FloatField(db_column='Maximum_Experiance')),
                ('MinimumExperiance', models.FloatField(db_column='Minimum_Experiance')),
                ('MaximumCTC', models.FloatField(db_column='Maximum_CTC')),
            ],
            options={
                'db_table': 'view_jobpostaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPostStakeHolders',
            fields=[
                ('JobPostId', models.BigIntegerField(db_column='Job_Post_ID', primary_key=True, serialize=False)),
                ('HMname', models.CharField(db_column='Hiring_Manager_Name', max_length=100)),
                ('HMemail', models.CharField(db_column='Hiring_Manager_Email', max_length=100)),
                ('BHname', models.CharField(db_column='Business_Head_Name', max_length=100)),
                ('BHemail', models.CharField(db_column='Business_Head_Email', max_length=100)),
                ('RecruiterName', models.CharField(db_column='Recruiter_Name', max_length=100)),
                ('RecruiterEmail', models.CharField(db_column='Recruiter_Email', max_length=100)),
            ],
            options={
                'db_table': 'view_jobpoststakeholders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPostUserRolesModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(db_column='Role_Name', max_length=100)),
                ('UserName', models.CharField(db_column='User_Name', max_length=50)),
                ('FullName', models.CharField(db_column='User_FullName', max_length=100)),
                ('Email', models.CharField(db_column='Email', max_length=100)),
            ],
            options={
                'db_table': 'view_user_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('JobPostId', models.AutoField(db_column='Job_Post_ID', primary_key=True, serialize=False)),
                ('JobCode', models.CharField(db_column='Job_Code', max_length=20, unique=True)),
                ('UserName', models.CharField(db_column='User_Name', max_length=20)),
                ('FirstName', models.CharField(db_column='First_Name', max_length=50)),
                ('LastName', models.CharField(db_column='Last_Name', max_length=50)),
                ('Email', models.CharField(db_column='Email', max_length=100)),
                ('EmploymentType', models.CharField(db_column='Employment_Type', max_length=30)),
                ('Duration', models.IntegerField(db_column='Dureation', null=True)),
                ('JobTitle', models.CharField(db_column='Job_Title', max_length=100)),
                ('JobDesc', models.CharField(db_column='Job_Desc', max_length=1000, null=True)),
                ('NoOfPositions', models.IntegerField(db_column='No_Of_Positions', null=True)),
                ('MinimumExperiance', models.IntegerField(db_column='Minimum_Experiance', default=0)),
                ('MaximumExperiance', models.IntegerField(db_column='Maximum_Experiance', default=0)),
                ('MaximumCTC', models.IntegerField(db_column='Maximum_CTC', default=0)),
                ('Qualification', models.CharField(db_column='Qualification', max_length=10, null=True)),
                ('OnBoardingDate', models.DateField(db_column='OnBoarding_Date')),
                ('POReference', models.CharField(db_column='PO_Ref', max_length=20, null=True)),
                ('CreatedBy', models.CharField(db_column='Created_By', max_length=20, null=True)),
                ('CreatedOn', models.DateTimeField(blank=True, db_column='Created_On', null=True)),
                ('ModifiedBy', models.CharField(db_column='Modified_By', max_length=20, null=True)),
                ('ModifiedOn', models.DateTimeField(blank=True, db_column='Modified_On', null=True)),
                ('BusinessUnit', models.ForeignKey(db_column='Business_Unit_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='managebusinessunit.businessunit')),
                ('Company', models.ForeignKey(db_column='Company_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='managecompany.company')),
                ('Customer', models.ForeignKey(db_column='Customer_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageCustomer.customer')),
                ('Industry', models.ForeignKey(db_column='Industry_Id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageIndustry.industry')),
                ('Location', models.ForeignKey(db_column='Location_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageLocation.location')),
                ('ServiceLine', models.ForeignKey(db_column='Service_Line_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='manageserviceline.serviceline')),
                ('Stage', models.ForeignKey(db_column='Stage_Id', null=True, on_delete=django.db.models.deletion.CASCADE, to='managestages.stage')),
            ],
            options={
                'db_table': 'HW_JobPost_Details',
            },
        ),
        migrations.CreateModel(
            name='JobPostApproval',
            fields=[
                ('jobPostApprovalId', models.AutoField(db_column='Job_Post_Approval_ID', primary_key=True, serialize=False)),
                ('approverName', models.CharField(db_column='Approver_Name', max_length=20)),
                ('FirstName', models.CharField(db_column='First_Name', max_length=50)),
                ('LastName', models.CharField(db_column='Last_Name', max_length=50)),
                ('Email', models.CharField(db_column='Email', max_length=100)),
                ('approvalStatus', models.CharField(db_column='Approval_Status', max_length=20)),
                ('approvalDate', models.DateField(blank=True, db_column='Approval_Date', null=True)),
                ('approvalComments', models.CharField(db_column='Approval_Comments', max_length=1000, null=True)),
                ('CreatedOn', models.DateTimeField(blank=True, db_column='Created_On', null=True)),
                ('Stage', models.ForeignKey(db_column='Stage_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='managestages.stage')),
                ('jobpost', models.ForeignKey(db_column='Job_Post_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobpost')),
                ('role', models.ForeignKey(db_column='Role_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'HW_JobPost_Approval',
            },
        ),
    ]
