# Generated by Django 4.0.7 on 2022-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='maximumctc',
            field=models.IntegerField(db_column='Maximum_CTC', default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='maximumexperiance',
            field=models.IntegerField(db_column='Maximum_Experiance', default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='minimumexperiance',
            field=models.IntegerField(db_column='Minimum_Experiance', default=0),
        ),
    ]
