# Generated by Django 4.0.8 on 2023-01-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0003_rename_maximumctc_jobpost_maximumctc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostStakeHolders',
            fields=[
                ('JobPostId', models.BigIntegerField(db_column='Job_Post_ID', primary_key=True, serialize=False)),
                ('HMname', models.CharField(db_column='Hiring_Manager_Name', max_length=100)),
                ('HMemail', models.CharField(db_column='Hiring_Manager_Email', max_length=100)),
                ('BHname', models.CharField(db_column='Business_Head_Name', max_length=100)),
                ('BHemail', models.CharField(db_column='Business_Head_Email', max_length=100)),
                ('RecruiterName', models.CharField(db_column='Recruiter_Name', max_length=100)),
                ('RecruiterEmail', models.CharField(db_column='Recruiter_Email', max_length=100)),
            ],
            options={
                'db_table': 'view_jobpoststakeholders',
                'managed': False,
            },
        ),
    ]
