# Generated by Django 4.0.8 on 2023-03-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0004_jobpoststakeholders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='ExperianceLevel',
        ),
    ]
