# Generated by Django 4.0.7 on 2022-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubBand',
            fields=[
                ('SubBandId', models.AutoField(db_column='Sub_Band_ID', primary_key=True, serialize=False)),
                ('SubBandName', models.CharField(db_column='Sub_Band_Name', max_length=5, null=True, unique=True)),
                ('BandId', models.IntegerField(db_column='Band_ID')),
                ('SubBandDesc', models.CharField(db_column='Sub_Band_Desc', max_length=500, null=True)),
                ('Active', models.BooleanField(db_column='Active', default=True)),
            ],
            options={
                'db_table': 'SubBand',
                'unique_together': {('SubBandName', 'BandId')},
            },
        ),
    ]
