# Generated by Django 4.0.7 on 2022-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageSubBand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subband',
            name='SubBandName',
            field=models.CharField(db_column='Sub_Band_Name', default=0, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
