# Generated by Django 4.0.7 on 2022-10-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationId', models.AutoField(db_column='Location_ID', primary_key=True, serialize=False)),
                ('LocationName', models.CharField(db_column='Location_Name', max_length=500, null=True)),
                ('Active', models.BooleanField(db_column='Active', default=True, null=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
    ]
