# Generated by Django 4.0.7 on 2022-10-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageLocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Active',
            field=models.BooleanField(db_column='Active', default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='LocationName',
            field=models.CharField(db_column='Location_Name', default='', max_length=500),
        ),
    ]
