# Generated by Django 4.0.7 on 2022-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageLocation', '0002_alter_location_active_alter_location_locationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='LocationName',
            field=models.CharField(db_column='Location_Name', default=' ', max_length=500),
        ),
    ]
