# Generated by Django 4.0.7 on 2022-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageLocation', '0003_alter_location_locationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='LocationName',
            field=models.CharField(db_column='Location_Name', max_length=50, unique=True),
        ),
    ]
