# Generated by Django 4.0.7 on 2022-11-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobpost', '0001_initial'),
        ('managestages', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('CandidateId', models.AutoField(db_column='Candidate_ID', primary_key=True, serialize=False)),
                ('CandidateCode', models.CharField(db_column='Candidate_Code', max_length=20, unique=True)),
                ('HRUserName', models.CharField(db_column='HR_User_Name', max_length=20, null=True)),
                ('CanFirstName', models.CharField(db_column='Can_First_Name', max_length=50, null=True)),
                ('CanLastName', models.CharField(db_column='Can_Last_Name', max_length=50, null=True)),
                ('Qualification', models.CharField(db_column='High_Qualification', max_length=30, null=True)),
                ('OverallExpYear', models.IntegerField(db_column='Overall_Exp_Year', null=True)),
                ('OverallExpMonth', models.IntegerField(db_column='Overall_Exp_Month', null=True)),
                ('ReleventExpYear', models.IntegerField(db_column='Relevent_Exp_Year', null=True)),
                ('ReleventExpMonth', models.IntegerField(db_column='Relevent_Exp_Month', null=True)),
                ('CurrentCTC', models.IntegerField(db_column='Current_CTC', null=True)),
                ('ExpectedCTC', models.IntegerField(db_column='Expected_CTC', null=True)),
                ('NegotiatedCTC', models.IntegerField(db_column='Negotiated_CTC', null=True)),
                ('ExpectedDOJ', models.DateField(db_column='Expected_DOJ')),
                ('CurrentOrganization', models.CharField(db_column='Current_Org', max_length=50, null=True)),
                ('CurrentJobLocation', models.CharField(db_column='Current_Job_Loc', max_length=50, null=True)),
                ('Skills', models.CharField(db_column='Skills', max_length=200, null=True)),
                ('Email', models.CharField(db_column='Email', max_length=100, null=True)),
                ('ConatctNo', models.CharField(db_column='Contact_No', max_length=20, null=True)),
                ('Resume', models.FileField(upload_to='')),
                ('AvgApprovedCTC', models.IntegerField(db_column='Avg_Approved_CTC', null=True)),
                ('AvgBillRate', models.IntegerField(db_column='Avg_Bill_Rate', null=True)),
                ('CreatedBy', models.CharField(db_column='Created_By', max_length=20, null=True)),
                ('CreatedOn', models.DateTimeField(blank=True, db_column='Created_On', null=True)),
                ('ModifiedBy', models.CharField(db_column='Modified_By', max_length=20, null=True)),
                ('ModifiedOn', models.DateTimeField(blank=True, db_column='Modified_On', null=True)),
                ('Jobpost', models.ForeignKey(db_column='Job_Post_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobpost')),
                ('Stage', models.ForeignKey(db_column='Stage_Id', null=True, on_delete=django.db.models.deletion.CASCADE, to='managestages.stage')),
            ],
            options={
                'db_table': 'HW_Candidate_Details',
            },
        ),
        migrations.CreateModel(
            name='CandidateApprovalModel',
            fields=[
                ('CandidateApprovalId', models.AutoField(db_column='Candidate_Approval_ID', primary_key=True, serialize=False)),
                ('approverName', models.CharField(db_column='Approver_Name', max_length=20)),
                ('FirstName', models.CharField(db_column='First_Name', max_length=50)),
                ('LastName', models.CharField(db_column='Last_Name', max_length=50)),
                ('Email', models.CharField(db_column='Email', max_length=100)),
                ('approvalStatus', models.CharField(db_column='Approval_Status', max_length=20)),
                ('approvalDate', models.DateField(blank=True, db_column='Approval_Date', null=True)),
                ('approvalComments', models.CharField(db_column='Approval_Comments', max_length=1000, null=True)),
                ('CreatedOn', models.DateTimeField(blank=True, db_column='Created_On', null=True)),
                ('Candidate', models.ForeignKey(db_column='Candidate_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('Stage', models.ForeignKey(db_column='Stage_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='managestages.stage')),
                ('role', models.ForeignKey(db_column='Role_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'HW_Candidate_Approval',
            },
        ),
    ]
