# Generated by Django 4.0.7 on 2022-12-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapprovalmodel',
            name='approvalStatus',
            field=models.CharField(db_column='Approval_Status', max_length=40),
        ),
    ]
