# Generated by Django 4.0.7 on 2022-12-09 10:23

import candidate.models.candidatemodel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_rename_conatctno_candidate_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Resume',
            field=models.FileField(upload_to=candidate.models.candidatemodel.Candidate.get_upload_path),
        ),
    ]
