# Generated by Django 4.0.8 on 2022-12-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_selected_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_candidates',
            name='Candidate_ID',
            field=models.ForeignKey(db_column='Candidate_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='candidate', to='candidate.candidate'),
        ),
    ]
