# Generated by Django 4.0.7 on 2022-12-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Comments',
            field=models.CharField(blank=True, db_column='Comments', max_length=500, null=True),
        ),
    ]
