# Generated by Django 4.0.8 on 2022-12-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_selected_candidates_candidate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_candidates',
            name='Candidate_ID',
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='Candidate',
            field=models.ForeignKey(db_column='Candidate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='candidate', to='candidate.candidate'),
        ),
    ]
