# Generated by Django 4.0.8 on 2022-12-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_remove_selected_candidates_candidate_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_candidates',
            name='Candidate',
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='candidate',
            field=models.ForeignKey(db_column='Candidate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate'),
        ),
    ]
