# Generated by Django 4.0.8 on 2023-01-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_candidatecategorymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_candidates',
            name='candidatecategory',
            field=models.ForeignKey(db_column='candidate_category_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidatecategorymodel'),
        ),
    ]
