# Generated by Django 4.0.8 on 2023-01-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageBand', '0003_alter_band_banddesc_alter_band_bandname'),
        ('ManageSubBand', '0002_alter_subband_subbandname'),
        ('candidate', '0010_alter_selected_candidates_candidatecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_candidates',
            name='band',
            field=models.ForeignKey(db_column='BandId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ManageBand.band'),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='subband',
            field=models.ForeignKey(db_column='SubBandId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ManageSubBand.subband'),
        ),
    ]
