# Generated by Django 4.0.7 on 2023-01-25 06:31

import candidate.models.selected_Candidates_Model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_remove_selected_candidates_ismqvariable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_candidates',
            name='VariablePercentage',
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='IsVariable',
            field=models.BooleanField(db_column='Is_Variable', default=False),
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='OfferLetter',
            field=models.FileField(db_column='Offer_Letter', null=True, upload_to=candidate.models.selected_Candidates_Model.Selected_Candidates.get_upload_path),
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='VariablePay',
            field=models.IntegerField(db_column='Variable_Pay', null=True),
        ),
    ]
