# Generated by Django 4.0.7 on 2023-01-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_remove_selected_candidates_variablepercentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_candidates',
            name='IsVariable',
            field=models.BooleanField(db_column='Is_Variable', default=None, null=True),
        ),
    ]
