# Generated by Django 4.0.7 on 2023-02-09 14:12

import candidate.models.selected_Candidates_Model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageBand', '0003_alter_band_banddesc_alter_band_bandname'),
        ('ManageDesignation', '0004_alter_designation_designationname'),
        ('ManageSubBand', '0002_alter_subband_subbandname'),
        ('candidate', '0014_alter_selected_candidates_isvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_candidates',
            name='candidatecategory',
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='BGVStatus',
            field=models.CharField(db_column='BGV_Status', default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='JoiningBonus',
            field=models.FloatField(db_column='Joining_Bonus', default=None, null=True),
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='ShiftAllowance',
            field=models.FloatField(db_column='Shift_Allowance', default=None, null=True),
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='VariablePerc',
            field=models.FloatField(db_column='Variable_Perc', default=0, null=True),
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='VerificationComments',
            field=models.CharField(db_column='Verification_Comments', default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='selected_candidates',
            name='VerificationStatus',
            field=models.CharField(db_column='Verification_Status', default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='Created_By',
            field=models.CharField(db_column='CreatedBy', default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='Created_on',
            field=models.DateField(db_column='Createdon', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='DateOfJoining',
            field=models.DateField(db_column='Date_Of_Joining', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='EmployeeID',
            field=models.CharField(db_column='Employee_ID', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='FinalCTC',
            field=models.FloatField(db_column='Final_CTC', default=0),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='FixedCTC',
            field=models.FloatField(db_column='Fixed_CTC', default=0),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='HRCID',
            field=models.CharField(db_column='HRC_ID', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='MQVariable',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='Modified_By',
            field=models.CharField(db_column='ModifiedBy', default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='Modified_On',
            field=models.DateField(db_column='ModifiedOn', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='OfferLetter',
            field=models.FileField(db_column='Offer_Letter', default=None, null=True, upload_to=candidate.models.selected_Candidates_Model.Selected_Candidates.get_upload_path),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='VariablePay',
            field=models.FloatField(db_column='Variable_Pay', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='band',
            field=models.ForeignKey(db_column='BandId', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ManageBand.band'),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='designation',
            field=models.ForeignKey(db_column='Designation_ID', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ManageDesignation.designation'),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='subband',
            field=models.ForeignKey(db_column='SubBandId', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ManageSubBand.subband'),
        ),
    ]
