# Generated by Django 4.0.7 on 2023-02-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_selected_candidates_joiningbonusletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_candidates',
            name='Duration',
            field=models.IntegerField(db_column='Duration', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='EndDate',
            field=models.DateTimeField(blank=True, db_column='EndDate', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='selected_candidates',
            name='NoOfHours',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
