# Generated by Django 4.0.8 on 2023-03-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageExperienceLevel', '0010_rename_max_experiencerange_experience_max_experience_and_more'),
        ('candidate', '0018_alter_selected_candidates_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ExperianceLevel',
            field=models.ForeignKey(db_column='Experience_Level_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageExperienceLevel.experience'),
        ),
    ]
