# Generated by Django 4.0.8 on 2023-03-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_alter_selected_candidates_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected_candidates',
            name='Responsibilities',
            field=models.CharField(db_column='Responsibilities', max_length=2000, null=True),
        ),
    ]
