# Generated by Django 4.0.7 on 2022-10-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('InsuranceAccidentLimitId', models.AutoField(db_column='Insurance_Accident_Limit_ID', primary_key=True, serialize=False)),
                ('BandID', models.IntegerField(db_column='Band_ID', null=True)),
                ('InsuranceLimit', models.FloatField(db_column='Insurance_Limit', default=0)),
                ('AccidentLimit', models.FloatField(db_column='Accident_Limit', default=0)),
                ('Active', models.BooleanField(db_column='Active', default=False)),
            ],
            options={
                'db_table': 'Insurance',
            },
        ),
    ]
