# Generated by Django 4.0.7 on 2022-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageInsurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='BandID',
        ),
        migrations.AddField(
            model_name='insurance',
            name='BandId',
            field=models.IntegerField(db_column='Band_ID', null=True, unique=True),
        ),
    ]
