# Generated by Django 4.0.7 on 2022-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageInsurance', '0002_remove_insurance_bandid_insurance_bandid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='Active',
            field=models.BooleanField(db_column='Active', default=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='BandId',
            field=models.IntegerField(db_column='Band_ID', default=0, unique=True),
            preserve_default=False,
        ),
    ]
