# Generated by Django 4.0.8 on 2023-02-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInformation',
            fields=[
                ('Id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Email', models.CharField(db_column='Email', max_length=50)),
                ('Department', models.CharField(db_column='Department', max_length=100)),
            ],
            options={
                'db_table': 'Department_Information',
            },
        ),
    ]
