# Generated by Django 4.0.7 on 2022-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('BandId', models.AutoField(db_column='Band_ID', primary_key=True, serialize=False)),
                ('BandName', models.CharField(db_column='Band_Name', max_length=10, null=True)),
                ('BandDesc', models.CharField(db_column='Band_Desc', max_length=10, null=True)),
                ('Active', models.BooleanField(db_column='Active', default=True)),
            ],
            options={
                'db_table': 'Band',
            },
        ),
    ]
