# Generated by Django 4.0.7 on 2022-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageBand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='BandName',
            field=models.CharField(db_column='Band_Name', max_length=10, null=True, unique=True),
        ),
    ]
