# Generated by Django 4.0.7 on 2022-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageBand', '0002_alter_band_bandname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='BandDesc',
            field=models.CharField(db_column='Band_Desc', max_length=10),
        ),
        migrations.AlterField(
            model_name='band',
            name='BandName',
            field=models.CharField(db_column='Band_Name', max_length=10, unique=True),
        ),
    ]
