# Generated by Django 4.0.7 on 2022-10-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('ServiceLineId', models.AutoField(db_column='Service_Line_ID', primary_key=True, serialize=False)),
                ('CompanyId', models.IntegerField(db_column='Company_ID', unique=True)),
                ('BusinessUnitId', models.IntegerField(db_column='Business_Unit_ID', unique=True)),
                ('ServiceLineName', models.CharField(db_column='Service_Line_Name', max_length=50, unique=True)),
                ('Acronym', models.CharField(db_column='Acronym', max_length=4, null=True, unique=True)),
                ('ServiceLineDesc', models.CharField(db_column='Service_Line_Desc', max_length=500, null=True)),
                ('Active', models.BooleanField(db_column='Active', default=True)),
            ],
            options={
                'db_table': 'ServiceLine',
            },
        ),
    ]
