# Generated by Django 4.0.7 on 2022-10-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageserviceline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceline',
            name='BusinessUnitId',
            field=models.IntegerField(db_column='Business_Unit_ID'),
        ),
        migrations.AlterField(
            model_name='serviceline',
            name='CompanyId',
            field=models.IntegerField(db_column='Company_ID'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceline',
            unique_together={('CompanyId', 'BusinessUnitId', 'ServiceLineName')},
        ),
    ]
