# Generated by Django 4.0.7 on 2022-10-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageserviceline', '0002_alter_serviceline_businessunitid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceline',
            name='ServiceLineName',
            field=models.CharField(db_column='Service_Line_Name', max_length=50),
        ),
    ]
