# Generated by Django 4.0.7 on 2022-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageserviceline', '0003_alter_serviceline_servicelinename'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceline',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='serviceline',
            name='Acronym',
            field=models.CharField(db_column='Acronym', max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='serviceline',
            unique_together={('CompanyId', 'BusinessUnitId', 'ServiceLineName', 'Acronym')},
        ),
    ]
